---

version: 2.1

workflows:
  main:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: curl -sfL https://goreleaser.com/static/run | bash
