---

version: 2.1

orbs:
  go: circleci/go@1.7.1

workflows:
  main:
    jobs:
      - build
  tag:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  build:
    executor:
      name: go/default
      tag: '1.19.3@sha256:4f16ed625733fe5d8e7452e075bdd666d0752e0c44643124e4d7c28a2f37351d'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  release:
    docker:
      - image: cimg/go:1.19.3@sha256:4f16ed625733fe5d8e7452e075bdd666d0752e0c44643124e4d7c28a2f37351d
    steps:
      - checkout
      - run: curl -sfL https://goreleaser.com/static/run | bash
